name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Verify style and run tests
        run: ./gradlew --no-daemon checkstyleMain checkstyleTest test

      - name: Build jars (app and fat jar)
        run: ./gradlew --no-daemon assemble shadowJar

      - name: Upload test and checkstyle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            build/reports/tests/test
            build/reports/checkstyle

      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: build/libs/*.jar


